CREATE TABLE IF NOT EXISTS reliable_event_outbox (
    id                BIGINT NOT NULL AUTO_INCREMENT,
    event_type        VARCHAR(128) NOT NULL,
    event_key         VARCHAR(192) NOT NULL,
    payload           JSON NOT NULL,
    headers           JSON NULL,
    status            TINYINT NOT NULL,
    next_attempt_at   DATETIME(3) NOT NULL,
    first_available_at DATETIME(3) NULL,
    attempt_count     INT NOT NULL DEFAULT 0,
    max_attempts      INT NOT NULL,
    lease_owner       VARCHAR(128) NULL,
    lease_until       DATETIME(3) NULL,
    version           BIGINT NOT NULL DEFAULT 0,
    last_error        VARCHAR(1024) NULL,
    created_at        DATETIME(3) NOT NULL,
    updated_at        DATETIME(3) NOT NULL,
    published_at      DATETIME(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_event_identity (event_type, event_key),
    KEY idx_publish_scan (status, next_attempt_at, id),
    KEY idx_lease_recovery (status, lease_until, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
