spring:
  application:
    name: reliable-event-example

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  otlp:
    tracing:
      export:
        enabled: true
      endpoint: ${EXAMPLE_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
